use_frameworks!

platform :ios, '10.0'

target 'SSnakePageControl_Example' do
  pod 'SSnakePageControl', :path => '../'

  target 'SSnakePageControl_Tests' do
    inherit! :search_paths

    
  end
end
